SECRET_KEY_BASE:

GOOGLE_CLIENT_ID:
GOOGLE_CLIENT_SECRET:
#GOOGLE_CALLBACK_URL=http://localhost:3000/oauth_callbacks
GOOGLE_CALLBACK_URL: https://localhost:3000/oauth_callbacks
#GOOGLE_CLIENT_ORIGIN=http://localhost:3000
GOOGLE_CLIENT_ORIGIN: https://localhost:3000
GOOGLE_API_KEY:

SIDEKIQ_USERNAME:
SIDEKIQ_PASSWORD:

DATABASE_USERNAME:
DATABASE_PASSWORD:
FACEBOOK_VALIDATION_TOKEN:

# Not in used yet
FACEBOOK_APP_ID:
FACEBOOK_APP_SECRET:
